// <auto-generated />
namespace BakcellPhoneWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class İnitial : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(İnitial));
        
        string IMigrationMetadata.Id
        {
            get { return "202105031603075_İnitial"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
